project:
  type: website
  output-dir: docs
  
website:
  title: "Stephen Carroll"
  favicon: MEDS/EDS-296/stephenccodes.github.io/favicon.png 
  navbar:
    #logo: images/favicon.png 
    #logo-alt: "My alt text here"
    left:
      - href: index.qmd
        text: Home
    # - about.qmd # Removed 5/28 because blank
      - href: resources.qmd
        text: Resources
      - href: blog_posts.qmd
        text: Blog
     #-text: CV
        #href: filepath_here
  page-footer: 
    background: light
    center: Copyright 2024, Stephen Carroll
    right: This website is built with {{< fa brands square-github title="square github icon" >}}
format:
  html:
    theme: styles.scss
    mainfont: Montserrat
      #light: minty
      #dark: solar
    #css: styles.css
    toc: false
    page-layout: full



